version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: blindbit-scan_app_1
      APP_PORT: 3000
      # we can whitelist, we have internal auth in BlindBit Scan
      PROXY_AUTH_ADD: "false"

  app:
    image: setavenger/blindbit-scan-frontend:dev-bd299ab@sha256:ae4ea99a726e481be13ef8fb6cee63241385f11c7daaf08ddf9a187ff424b405
    restart: on-failure
    stop_grace_period: 1m
    environment:
      NEXT_PUBLIC_BLINDBIT_SCAN_BASE_URL: "http://${DEVICE_DOMAIN_NAME}:${APP_BLINDBIT_SCAN_NODE_PORT}"
      NEXT_PUBLIC_BLINDBIT_SCAN_USER: "blindbit-scan-umbrel"
      NEXT_PUBLIC_BLINDBIT_SCAN_PASSWORD: ${APP_PASSWORD}
      NEXT_PUBLIC_BLINDBIT_SCAN_TOR_BASE_URL: "http://${APP_BLINDBIT_SCAN_API_HIDDEN_SERVICE}:${APP_BLINDBIT_SCAN_NODE_PORT}"
      NEXT_PUBLIC_BLINDBIT_SCAN_PORT: ${APP_BLINDBIT_SCAN_NODE_PORT}
  
  worker:
    image: setavenger/blindbit-scan:v0.1.0@sha256:00245f7444a2a76751d13dcf20e908901a8f1739cd516c2ddf88d51f9176c63e
    restart: on-failure
    stop_grace_period: 1m
    volumes:
      - ${APP_DATA_DIR}/data:/root/.blindbit-scan
    ports:
      - "${APP_BLINDBIT_SCAN_NODE_PORT}:${APP_BLINDBIT_SCAN_NODE_PORT}"
    environment:
      # Network configuration
      EXPOSE_HTTP: "${APP_BLINDBIT_SCAN_NODE_IP}:${APP_BLINDBIT_SCAN_NODE_PORT}"
      BLINDBIT_SERVER: "http://${APP_BLINDBIT_ORACLE_NODE_IP}:${APP_BLINDBIT_ORACLE_NODE_PORT}"
      ELECTRUM_SERVER: "${APP_ELECTRS_NODE_IP}:${APP_ELECTRS_NODE_PORT}"    
      NETWORK_CHAIN: "main"                             
      ELECTRUM_TOR: 0

      # Wallet configuration
      WALLET_DUST_LIMIT: 1000
      WALLET_LABEL_COUNT: 1
      WALLET_BIRTH_HEIGHT: 852000
      # WALLET_SCAN_SECRET_KEY: "your-scan-secret-key"     
      # WALLET_SPEND_PUB_KEY: "your-spend-pub-key"         

      # Authentication
      AUTH_USER: "blindbit-scan-umbrel"                        
      AUTH_PASS: ${APP_PASSWORD}

      LOG_LEVEL: trace
    networks:
      default:
        ipv4_address: $APP_BLINDBIT_SCAN_NODE_IP

  tor:
    image: getumbrel/tor:0.4.7.8@sha256:2ace83f22501f58857fa9b403009f595137fa2e7986c4fda79d82a8119072b6a
    user: "1000:1000"
    restart: on-failure
    volumes:
      - ${APP_DATA_DIR}/torrc:/etc/tor/torrc:ro
      - ${TOR_DATA_DIR}:/data
    environment:
      HOME: "/tmp"
    networks:
        default:
