version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: blindbit-oracle_app_1
      APP_PORT: 3000

  app:
    image: setavenger/blindbit-oracle-frontend:dev-e828b25@sha256:5636a0f6a607c26216275d227b9cc3146e2bdde6c8ddb74e6de3a490a6674729
    restart: on-failure
    stop_grace_period: 1m
    environment:
      NEXT_PUBLIC_BLINDBIT_ORACLE_BASE_URL: "http://${DEVICE_DOMAIN_NAME}:${APP_BLINDBIT_ORACLE_NODE_PORT}"
      NEXT_PUBLIC_BLINDBIT_ORACLE_TOR_BASE_URL: "http://${APP_BLINDBIT_ORACLE_API_HIDDEN_SERVICE}:${APP_BLINDBIT_ORACLE_NODE_PORT}"
      NEXT_PUBLIC_BLINDBIT_ORACLE_PORT: ${APP_BLINDBIT_ORACLE_NODE_PORT}
  
  worker:
    image: setavenger/blindbit-oracle:dev-0ffb504@sha256:743b65a6df04e01e1dfbc9d16b0cc5acb9236d3488983b79fcdd6c973bd273b6
    restart: on-failure
    stop_grace_period: 1m
    volumes:
      - ${APP_DATA_DIR}/data:/root/.blindbit-oracle
    ports:
      - "${APP_BLINDBIT_ORACLE_NODE_PORT}:${APP_BLINDBIT_ORACLE_NODE_PORT}"
    environment:
      HOST: "${APP_BLINDBIT_ORACLE_NODE_IP}:${APP_BLINDBIT_ORACLE_NODE_PORT}"
      CHAIN: main
      SYNC_START_HEIGHT: 842300 # a couple hours before Bip 352 was merged
      MAX_PARALLEL_REQUESTS: 4
      MAX_PARALLEL_TWEAK_COMPUTATIONS: 4
      TWEAKS_CUT_THROUGH_WITH_DUST_FILTER: 1

      # Bitcoin Core connection details
      RPC_ENDPOINT: "http://${APP_BITCOIN_NODE_IP}:${APP_BITCOIN_RPC_PORT}"
      RPC_USER: $APP_BITCOIN_RPC_USER
      RPC_PASS: $APP_BITCOIN_RPC_PASS
    networks:
      default:
        ipv4_address: $APP_BLINDBIT_ORACLE_NODE_IP

  tor:
    image: getumbrel/tor:0.4.7.8@sha256:2ace83f22501f58857fa9b403009f595137fa2e7986c4fda79d82a8119072b6a
    user: "1000:1000"
    restart: on-failure
    volumes:
      - ${APP_DATA_DIR}/torrc:/etc/tor/torrc:ro
      - ${TOR_DATA_DIR}:/data
    environment:
      HOME: "/tmp"
    networks:
        default:
