version: "3.7"

services:
  app_proxy:
    environment:
      # <app-id>_<web-container-name>_1
      # e.g. 'btc-rpc-explorer_web_1'
      # Note that the '_1' at the end is needed
      APP_HOST: blindbit-oracle_worker_1
      APP_PORT: 8080
        # we can whitelist, nothing private is being collected by BlindBit Oracle
      PROXY_AUTH_WHITELIST: "*"
  
  worker:
    image: setavenger/blindbit-oracle:v0.1.0-test@sha256:eda2cadcf3f131f4ae1a73a1b2132b8e6fc6e4929622b224ee2022a751931a18
    restart: on-failure
    stop_grace_period: 1m
    volumes:
      # Uncomment to mount your data directories inside
      # the Docker container for storing persistent data
      - ${APP_DATA_DIR}/data:/root/.blindbit-oracle
    environment:
      HOST: "0.0.0.0:8080"
      CHAIN: main
      SYNC_START_HEIGHT: 850000
      MAX_PARALLEL_REQUESTS: 8
      MAX_PARALLEL_TWEAK_COMPUTATIONS: 8
      TWEAKS_CUT_THROUGH_WITH_DUST_FILTER: 1

      # Bitcoin Core connection details
      RPC_ENDPOINT: "http://${APP_BITCOIN_NODE_IP}:${APP_BITCOIN_RPC_PORT}"
      RPC_USER: $APP_BITCOIN_RPC_USER
      RPC_PASS: $APP_BITCOIN_RPC_PASS
      # Pass any environment variables to your app for configuration in the form:
      # VARIABLE_NAME: value
      #
      # Here are all the Umbrel provided variables that you can pass through to
      # your app
      # System level environment variables
      # $DEVICE_HOSTNAME - Umbrel server device hostname (e.g. "umbrel")
      # $DEVICE_DOMAIN_NAME - A .local domain name for the Umbrel server (e.g. "umbrel.local")
      #
      # Tor proxy environment variables
      # $TOR_PROXY_IP - Local IP of Tor proxy
      # $TOR_PROXY_PORT - Port of Tor proxy
      #
      # App specific environment variables
      # $APP_HIDDEN_SERVICE - The address of the Tor hidden service your app will be exposed at
      # $APP_PASSWORD - Unique plain text password that can be used for authentication in your app, shown to the user in the Umbrel UI
      # $APP_SEED - Unique 256 bit long hex string (128 bits of entropy) deterministically derived from user's Umbrel seed and your app's ID
