version: "3.7"

services:
  app_proxy:
    environment:
      # <app-id>_<web-container-name>_1
      # e.g. 'btc-rpc-explorer_web_1'
      # Note that the '_1' at the end is needed
      # APP_HOST: blindbit-oracle_worker_1
      APP_HOST: ${APP_BLINDBIT_ORACLE_NODE_IP}
      APP_PORT: ${APP_BLINDBIT_ORACLE_NODE_PORT}
      # nothing private is being collected by BlindBit Oracle
      PROXY_AUTH_ADD: "false"
  
  worker:
    image: setavenger/blindbit-oracle:v0.1.0@sha256:cdeebe4b19ac5b71e54cf894059f397d212663f0f29d51094f2fc47eb7ea470e
    restart: on-failure
    stop_grace_period: 1m
    volumes:
      - ${APP_DATA_DIR}/data:/root/.blindbit-oracle
    environment:
      HOST: "${APP_BLINDBIT_ORACLE_NODE_IP}:${APP_BLINDBIT_ORACLE_NODE_PORT}"
      CHAIN: main
      SYNC_START_HEIGHT: 850000
      MAX_PARALLEL_REQUESTS: 8
      MAX_PARALLEL_TWEAK_COMPUTATIONS: 8
      TWEAKS_CUT_THROUGH_WITH_DUST_FILTER: 1

      # Bitcoin Core connection details
      RPC_ENDPOINT: "http://${APP_BITCOIN_NODE_IP}:${APP_BITCOIN_RPC_PORT}"
      RPC_USER: $APP_BITCOIN_RPC_USER
      RPC_PASS: $APP_BITCOIN_RPC_PASS
    networks:
      default:
        ipv4_address: $APP_BLINDBIT_ORACLE_NODE_IP
